export type OpenDesignMode = 'deck';

export type OpenDesignScenario = 'marketing' | 'product' | 'operation';

export type OpenDesignManifest = {
  mode: OpenDesignMode;
  scenario: OpenDesignScenario[];
  artifact: 'open-slide-deck';
  preview: {
    type: 'open-slide';
    fullRoute: string;
    shareRoute: string;
  };
  designSystem: {
    name: string;
    requires: Array<'brand-tokens' | 'wireframes' | 'content-schema' | 'preflight' | 'self-review'>;
  };
  fidelity: 'production';
  exports: Array<'html' | 'pdf' | 'pptx'>;
};

export type DiscoveryQuestion = {
  id: string;
  label: string;
  required: boolean;
  guidance: string;
};

export type DesignDirection = {
  id: string;
  name: string;
  whenToUse: string;
  guardrails: string[];
};

export type SelfReviewItem = {
  dimension: 'content' | 'brand' | 'layout' | 'artifact' | 'export';
  question: string;
  passCriteria: string;
};

export const openDesignManifest: OpenDesignManifest = {
  mode: 'deck',
  scenario: ['marketing', 'product', 'operation'],
  artifact: 'open-slide-deck',
  preview: {
    type: 'open-slide',
    fullRoute: '/s/tech-insider-channel-plan',
    shareRoute: '/s/tech-insider-channel-plan-share',
  },
  designSystem: {
    name: 'TECH INSIDER SDD',
    requires: ['brand-tokens', 'wireframes', 'content-schema', 'preflight', 'self-review'],
  },
  fidelity: 'production',
  exports: ['html', 'pdf', 'pptx'],
};

export const discoveryQuestions: DiscoveryQuestion[] = [
  {
    id: 'surface',
    label: 'Surface',
    required: true,
    guidance: 'Confirm whether the output is a 16:9 proposal deck, share deck, exported PDF, PPTX handoff, or separate 9:16 artifact.',
  },
  {
    id: 'audience',
    label: 'Audience',
    required: true,
    guidance: 'Identify whether the deck is for internal editorial planning, executives, partners, sponsors, or public sharing.',
  },
  {
    id: 'tone',
    label: 'Tone',
    required: true,
    guidance: 'Choose the communication posture: strategic, editorial, sales-oriented, operational, or teaching-oriented.',
  },
  {
    id: 'brand-context',
    label: 'Brand Context',
    required: true,
    guidance: 'Use TECH INSIDER brand tokens by default. Do not introduce a different design system unless the user explicitly asks.',
  },
  {
    id: 'scale',
    label: 'Scale',
    required: true,
    guidance: 'Confirm target slide count, density, and whether the palette/reference appendix should be included.',
  },
];

export const designDirections: DesignDirection[] = [
  {
    id: 'tech-utility',
    name: 'Tech Utility',
    whenToUse: 'Default direction for business technology strategy, channel planning, operating models, and analytical pages.',
    guardrails: [
      'Use restrained brand blues and paper backgrounds.',
      'Prefer structured grids, cards, bands, and metadata panels.',
      'Avoid decorative gradients, random arcs, and oversized marketing hero treatment after the cover.',
    ],
  },
  {
    id: 'editorial-monocle',
    name: 'Editorial Monocle',
    whenToUse: 'Use when the deck needs a magazine-like feature mood, strong issue framing, or premium editorial storytelling.',
    guardrails: [
      'Keep Chinese text in OpenSlide layers.',
      'Use stronger typographic hierarchy, pull quotes, and image-led composition.',
      'Do not let editorial styling reduce scanability for business readers.',
    ],
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    whenToUse: 'Use for executive summaries, simple proposals, and low-noise stakeholder updates.',
    guardrails: [
      'Use fewer cards and more whitespace.',
      'Keep all content claims precise and short.',
      'Do not remove page numbers, brand marks, or structural wayfinding.',
    ],
  },
];

export const selfReviewChecklist: SelfReviewItem[] = [
  {
    dimension: 'content',
    question: 'Does every slide make one clear claim or describe one clear module?',
    passCriteria: 'No slide depends on decorative text or vague filler to make sense.',
  },
  {
    dimension: 'brand',
    question: 'Are all colors, typography, cards, tags, and page numbers drawn from the SDD tokens?',
    passCriteria: 'No one-off colors, random shapes, or non-brand visual language appear.',
  },
  {
    dimension: 'layout',
    question: 'Can the page be regenerated by the same component with different content?',
    passCriteria: 'Content is in `content.ts`; reusable structure is in `components.tsx` or `wireframes.ts`.',
  },
  {
    dimension: 'artifact',
    question: 'Is the output an inspectable OpenSlide artifact rather than a flat image pretending to be a slide?',
    passCriteria: 'All Chinese text, page numbers, tags, and data labels are rendered by OpenSlide.',
  },
  {
    dimension: 'export',
    question: 'Did the full and share variants still build and load after the change?',
    passCriteria: 'Build passes; full deck has 8 pages; share deck has 7 pages unless the user requested a variant change.',
  },
];
